// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesforceDataConnector.Infrastructure.Database;

#nullable disable

namespace SalesforceDataConnector.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207192542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanReceiveAlert")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SystemModstamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.ToTable("Salesforce_Contact");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.Opportunity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceProviderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SystemModstamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Salesforce_Opportunity");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.ServiceProvider", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SystemModstamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Salesforce_Service_Provider");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.Contact", b =>
                {
                    b.HasOne("SalesforceDataConnector.Domain.Entities.Opportunity", null)
                        .WithMany("Contacts")
                        .HasForeignKey("OpportunityId");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.Opportunity", b =>
                {
                    b.HasOne("SalesforceDataConnector.Domain.Entities.ServiceProvider", null)
                        .WithMany("Opportunities")
                        .HasForeignKey("ServiceProviderId");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.Opportunity", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("SalesforceDataConnector.Domain.Entities.ServiceProvider", b =>
                {
                    b.Navigation("Opportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
